#!/bin/bash

python -m exp.run_mol_exp \
  --device 0 \
  --start_seed 0 \
  --stop_seed 0\
  --dataset Model_NN_Graph \
  --train_eval_period 20 \
  --epochs 1 \
  --batch_size 16 \
  --drop_rate 0.0 \
  --drop_position lin2 \
  --emb_dim 128 \
  --max_dim 7 \
  --final_readout sum \
  --init_method sum \
  --lr 0.001 \
  --graph_norm bn \
  --model cin \
  --nonlinearity relu \
  --num_layers 6 \
  --readout sum \
  --max_ring_size 7 \
  --task_type regression \
  --eval_metric mae \
  --minimize \
  --lr_scheduler 'ReduceLROnPlateau' \
  --use_coboundaries True \
  --use_edge_features \
  --early_stop \
  --lr_scheduler_patience 20 \
  --dump_curves \
  --preproc_jobs 32 \
  --task cola \
  --node_feature_type temp_inputs
